// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0ECLNSbr_8n7qYqB032oXq2T_Dh3kElM',
    appId: '1:1054275207797:web:af9dc2980863e221aaee3c',
    messagingSenderId: '1054275207797',
    projectId: 'fir-40599',
    authDomain: 'fir-40599.firebaseapp.com',
    storageBucket: 'fir-40599.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPHAUzQ1PrWrTSIh2u2rGaxhtjzOMpQbY',
    appId: '1:1054275207797:android:5b2e539eca2da4e4aaee3c',
    messagingSenderId: '1054275207797',
    projectId: 'fir-40599',
    storageBucket: 'fir-40599.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGetoHEskHxjjq_xLRwpSUpejhRHD8NPE',
    appId: '1:1054275207797:ios:d71e46e5fda1310eaaee3c',
    messagingSenderId: '1054275207797',
    projectId: 'fir-40599',
    storageBucket: 'fir-40599.appspot.com',
    iosClientId: '1054275207797-htkb2oumasclnb2dn8rt925u18amp0bk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGetoHEskHxjjq_xLRwpSUpejhRHD8NPE',
    appId: '1:1054275207797:ios:7a53845284d9cc35aaee3c',
    messagingSenderId: '1054275207797',
    projectId: 'fir-40599',
    storageBucket: 'fir-40599.appspot.com',
    iosClientId: '1054275207797-k5um70919hc5monnv07fb2upjkv6qo2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin.RunnerTests',
  );
}
