// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXfRDF4nS0csduW-0HijPpdcpcvwq-eTE',
    appId: '1:167791056620:web:299e5f02881b610e9077c9',
    messagingSenderId: '167791056620',
    projectId: 'fir-example-9af26',
    authDomain: 'fir-example-9af26.firebaseapp.com',
    storageBucket: 'fir-example-9af26.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCklaRGouqfu9RkW0cxMsYsYXz2alkUNF8',
    appId: '1:167791056620:android:47f7bb1a03d82fe09077c9',
    messagingSenderId: '167791056620',
    projectId: 'fir-example-9af26',
    storageBucket: 'fir-example-9af26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4fz2PBBZiYBA3BMAGr8Yu5Zc27q3s3gE',
    appId: '1:167791056620:ios:c21cdbaded56a2a29077c9',
    messagingSenderId: '167791056620',
    projectId: 'fir-example-9af26',
    storageBucket: 'fir-example-9af26.appspot.com',
    iosClientId: '167791056620-c554ug6gh0a9qc83t58iquae2mesgh1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4fz2PBBZiYBA3BMAGr8Yu5Zc27q3s3gE',
    appId: '1:167791056620:ios:161bc31bdcfc580f9077c9',
    messagingSenderId: '167791056620',
    projectId: 'fir-example-9af26',
    storageBucket: 'fir-example-9af26.appspot.com',
    iosClientId: '167791056620-patt29jd7t0kb7jqn128khg4tinbir3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExample.RunnerTests',
  );
}
